name: Linux Container Node Workflow

on: 
  push:
    branches:
      - main
  workflow_dispatch:
      
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    
    env:
      MODEL_NAME: MODEL_NAME

    steps:
    - uses: actions/checkout@v2

    - name: Download AzureML Model
      id: download-model
      uses: SSC-DSAI/azureml-download-model-github-action@main
      with:
        model-name: ${{ secrets.MODEL_NAME }}
        resource-group: ${{ secrets.RESOURCE_GROUP }}
        spn-id: ${{ secrets.SPN_ID}}
        spn-pwd: ${{ secrets.SPN_PWD }}
        subs-id: ${{ secrets.SUBS_ID }}
        tenant-id: ${{ secrets.TENANT_ID}}
        workspace-name: ${{ secrets.WORKSPACE_NAME }}
    
    - name: Relocate and Rename Model File
      run: mv ./${{ steps.download-model.outputs.filepath }} ./src/trained_model.bin
      shell: bash 

    - uses: azure/docker-login@v1
      with:
        login-server: <acr-host-url>
        username: ${{ secrets.SPN_ID }}
        password: ${{ secrets.SPN_PWD }}

    - run: |
        docker build . -t <acr-host-url>/<app-name>:${{ github.sha }}
        docker push <acr-host-url>/<app-name>:${{ github.sha }}

    - uses: azure/webapps-deploy@v2
      with:
        app-name: '<app-name>'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile}}
        images: '<acr-host-url>/<app-name>:${{ github.sha }}'